apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: maqgcgh1w-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/maqgcgh1w-java-springboot-gitops